name: Update Flex endpoint

on:
    push:
        branches:
            - main

defaults:
    run:
        shell: bash

jobs:
    qa:
        uses: ./.github/workflows/qa.yml
        permissions:
            contents: read

    call-flex-update:
        needs: qa
        concurrency: flex-update-${{ github.ref }}
        uses: symfony/recipes/.github/workflows/callable-flex-update.yml@main
        permissions:
            contents: write
        with:
            branch: main
        secrets:
            token: ${{ secrets.GITHUB_TOKEN }}
